[solution]
name = "ML Team-dsa-sparse-attn"                   # Customize before submitting
definition = "dsa_sparse_attention_h16_ckv512_kpe64_topk2048_ps64"
author = "ML Team"                                  # Customize before submitting

[build]
language = "cuda"                                      # python | triton | cuda
entry_point = "kernel.cu::dsa_forward"
destination_passing_style = false
binding = "torch"                                     # torch | tvm-ffi
